### ISSUE TITLE
Can I use rack-unreloader not only with Rack?

### ISSUE THREAD

**Issue by Serhiy-Nazarov** [jeremyevans/rack-unreloader#12]
I want to use rack-unreloader with sneakers (without Rack). I can't find any limitation for that. what did I lose?

**Comment by jeremyevans** [comment]
rack-unreloader does not have a dependency on rack itself, and you can use it outside of rack, as described in the README: https://github.com/jeremyevans/rack-unreloader#label-Usage+Outside+Rack
