### ISSUE TITLE
rubydoc.info rendering broken after 1.7.0

### ISSUE THREAD

**Issue by fdr** [jeremyevans/rack-unreloader#16]
The last version of Unreloader that renders properly for me is https://www.rubydoc.info/gems/rack-unreloader/1.7.0/Rack/Unreloader.

Starting in 1.8.0, it yields various kinds of mostly blank pages.

**Comment by jeremyevans** [comment]
I checked 1.8.0 and 2.1.0 and both displayed similar to 1.7.0 for me.

Note that even if the display was broken, it would be better to report this to rubydoc.info unless you could determine it was due to a bug in rack-unreloader.
