### ISSUE TITLE
rack-unloader fails in roda if java is required using jruby (v1.6.8)

### ISSUE THREAD

**Issue by cmichon** [jeremyevans/rack-unreloader#4]
Hi,

I'm building a small test case using roda, sequel, H2 and jruby.
I'm on Windows OS, using JDK 8u25. Jruby is 1.6.8, in 1.8 mode.

rack-unloader fails unless I remove sequel, and I traced the failure to requiring 'java' in config,ru:

my config.ru:
```ruby
require 'java'
require 'rack/unreloader'
Unreloader = Rack::Unreloader.new{App}
require 'roda'
Unreloader.require './app.rb'
run Unreloader
```

Trace:
```
ArgumentError: invalid package module
  get_proxy_or_package_under_package at org/jruby/javasupport/JavaUtilities.java:54
                      method_missing at file:/C:/dev/rb/lib/jruby.jar!/builtin/javasupport/java.rb:51
                         all_classes at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-unreloader-1.1.0/lib/rack/unreloader.rb:253
                         each_object at org/jruby/RubyObjectSpace.java:167
                                each at org/jruby/RubyEnumerator.java:195
                         all_classes at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-unreloader-1.1.0/lib/rack/unreloader.rb:252
                             prepare at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-unreloader-1.1.0/lib/rack/unreloader.rb:213
                           safe_load at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-unreloader-1.1.0/lib/rack/unreloader.rb:140
                require_dependencies at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-unreloader-1.1.0/lib/rack/unreloader.rb:118
                                each at org/jruby/RubyArray.java:1620
                require_dependencies at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-unreloader-1.1.0/lib/rack/unreloader.rb:100
                             require at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-unreloader-1.1.0/lib/rack/unreloader.rb:332
                     new_from_string at development.ru:5
                       instance_eval at org/jruby/RubyKernel.java:2074
                          initialize at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-1.6.0/lib/rack/builder.rb:55
                     new_from_string at development.ru:0
                                eval at org/jruby/RubyKernel.java:1112
                     new_from_string at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-1.6.0/lib/rack/builder.rb:49
                          parse_file at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-1.6.0/lib/rack/builder.rb:40
   build_app_and_options_from_config at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-1.6.0/lib/rack/server.rb:299
                                 app at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-1.6.0/lib/rack/server.rb:208
                         wrapped_app at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-1.6.0/lib/rack/server.rb:336
                               start at C:/dev/snip-roda/vendor/bundle/jruby/1.8/gems/rack-1.6.0/lib/rack/server.rb:272
                              (root) at server.rb:3
```

**Comment by jeremyevans** [comment]
Can you try working around this by using a block for all unreloader requires:

```ruby
Unreloader.require('./app.rb'){'App'} 
```

The block lists the constants that should be undefined when the file is reloaded.  That way you don't need to use `ObjectSpace`.  This appears to be a jruby bug:

```ruby
Module.method_defined?(:name) # => true # all modules should response to name
ObjectSpace.each_object(Module).each do |mod| p mod unless mod.respond_to?(:name) end
```

The output is:

```
Java::OrgJrubyRuntimeBuiltinName
Java::OrgJrubyRuntimeMarshalName
Java::JavaxName
Java::JavaxManagementName
Java::OrgJrubyUtilName
Java::OrgJrubyExtReadlineName
Java::JavaNioName
Java::JavaNioChannelsName
Java::JavaNetName
Java::OrgJrubyRuntimeName
Java::OrgJrubyJavaUtilName
Java::OrgJrubyExtName
Java::OrgJrubyRuntimeLoadName
Java::OrgJrubyName
Java::OrgName
Java::OrgJrubyLexerName
Java::OrgJrubyLexerYaccName
Java::OrgJrubyAstName
Java::JavaLangReflectName
Java::JavaUtilName
Java::JavaUtilRegexName
Java::JavaIoName
JavaPackageModuleTemplate
Java::Java
Java::Default
Java::JavaLang
```

So those are ruby modules that don't respond to name, when they probably should.  I'll post a bug on the jruby bugtracker.

**Comment by cmichon** [comment]
Or we could filter these out by class name patterns (easier) inside roda.
Jruby 1.6.8 has no more devs these days ...

**Comment by jeremyevans** [comment]
This is still a problem in the latest jruby release.  You wouldn't want to filter by class name patterns, you could just check if `respond_to?(:name)` is true.  But I don't like to add workarounds for implementation bugs, especially on jruby where ObjectSpace isn't even enabled by default.

For best performance, you will always want to use a block for the requires, as scanning ObjectSpace adds a lot of overhead.

**Comment by cmichon** [comment]
OK I'll go the block way. I'll keep you posted.

Please note Java::* are java classes not ruby classes.

**Comment by jeremyevans** [comment]
If jruby has the Java classes as an instance of Module, they should be implementing the methods that Module defines.

Since I think this is a jruby bug, I'm going to close it now.  If the jruby guys don't think it is a bug, I'll reopen.

**Comment by cmichon** [comment]
The block way worked perfectly: 
```ruby
Unreloader.require('./app.rb'){'App'} 
```

Thanks Jeremy!

**Comment by rosenfeld** [comment]
> But I don't like to add workarounds for implementation bugs, especially on jruby where ObjectSpace isn't even enabled by default.

It seems to be enabled by default, at least on JRuby 9.0.5.0. ActiveSupport::Dependencies somehow is able to handle JRuby so I guess it should be possible for rack-unreloader as well. It would be awesome if it could support JRuby.

**Comment by jeremyevans** [comment]
@rosenfeld I believe this problem is fixed in JRuby 1.7.22+ and all versions of JRuby 9+.  If you are having problems with it, please post which JRuby version you are using, the code you are using, and a backtrace.

**Comment by rosenfeld** [comment]
```ruby
if ENV['RACK_ENV'] == 'development'
  require 'rack/unreloader'
  Unreloader = Rack::Unreloader.new{App}
  require 'roda'
  Unreloader.require('./app.rb')
  run Unreloader
else
  require_relative './app'
  run App
end
```

```
$ bin/puma
Puma starting in single mode...
* Version 3.4.0 (jruby 9.0.5.0 - ruby 2.2.3), codename: Owl Bowl Brawl
* Min threads: 0, max threads: 16
* Environment: development
! Unable to load application: ArgumentError: invalid package module
ArgumentError: invalid package module
  get_proxy_or_package_under_package at org/jruby/javasupport/JavaUtilities.java:54
                                name at uri:classloader:/jruby/java/java_package_module_template.rb:19
                block in all_classes at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:375
                         each_object at org/jruby/RubyObjectSpace.java:185
                                each at org/jruby/RubyEnumerator.java:293
                                each at org/jruby/RubyEnumerator.java:299
                         all_classes at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:374
                             prepare at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:315
                           safe_load at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:246
       block in require_dependencies at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:154
                                each at org/jruby/RubyArray.java:1560
                require_dependencies at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:143
                             require at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader.rb:83
            block in new_from_string at config.ru:5
                       instance_eval at org/jruby/RubyBasicObject.java:1633
                          initialize at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rack-2.0.1/lib/rack/builder.rb:55
                              <eval> at config.ru:1
                                eval at org/jruby/RubyKernel.java:976
                     new_from_string at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rack-2.0.1/lib/rack/builder.rb:49
                          parse_file at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/rack-2.0.1/lib/rack/builder.rb:40
                         load_rackup at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/puma-3.4.0-java/lib/puma/configuration.rb:313
                                 app at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/puma-3.4.0-java/lib/puma/configuration.rb:242
                       load_and_bind at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/puma-3.4.0-java/lib/puma/runner.rb:123
                                 run at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/puma-3.4.0-java/lib/puma/single.rb:84
                                 run at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/puma-3.4.0-java/lib/puma/launcher.rb:172
                                 run at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/puma-3.4.0-java/lib/puma/cli.rb:74
                               <top> at /home/rodrigo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/puma-3.4.0-java/bin/puma:10
                                load at org/jruby/RubyKernel.java:955
                               <top> at bin/puma:16
```

**Comment by jeremyevans** [comment]
@rosenfeld Thanks.  Can you run this and post what it outputs: `jruby -ve "ObjectSpace.each_object(Module).each do |mod| p mod unless mod.respond_to?(:name) end"`

**Comment by rosenfeld** [comment]
`jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.91-b14 on 1.8.0_91-b14 +jit [linux-amd64]`

**Comment by jeremyevans** [comment]
Looks like this is still a problem in JRuby <9.1, inspite of the fact that the jruby developers marked it as fixed in 1.7.22 and 9.0.1.0.  Can you upgrade to JRuby 9.1+?

Anyway, if you'd like this fixed in JRuby 9.0.x, you'll have to ask the JRuby developers to backport the bug fix to the 9.0 branch.  As stated earlier, I don't like to add workarounds for ruby implementation bugs.

**Comment by rosenfeld** [comment]
Thanks, @jeremyevans, worked with JRuby 9.1.2.0. It would be great to add that note in the README.

**Comment by jeremyevans** [comment]
I've updated the README to mention that JRuby 9.1+ is supported, and older versions of JRuby work if you use procs to specify the constants to unload.

**Comment by rosenfeld** [comment]
thanks

**Comment by rosenfeld** [comment]
Sorry, @jeremyevans, but it doesn't quite work fine transparently even with JRuby 9.1.2.0. That error when starting the app stopped but if I change some file then I get something like this:

```
2016-07-14 13:37:53 -0300: Rack app error: #<ArgumentError: Java package 'org.apache.poi.ss.usermodel' does not have a method `send' with 2 arguments>
org/jruby/javasupport/JavaPackage.java:267:in `method_missing'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:264:in `remove_constant'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:292:in `block in remove_constants'
org/jruby/RubyHash.java:1511:in `each_key'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/stdlib/set.rb:306:in `each'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:292:in `remove_constants'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:285:in `remove'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:306:in `prepare'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:246:in `safe_load'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:133:in `block in reload!'
org/jruby/RubyArray.java:1593:in `each'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader/reloader.rb:132:in `reload!'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader.rb:118:in `reload!'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader.rb:74:in `block in call'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/gems/shared/gems/rack-unreloader-1.5.0/lib/rack/unreloader.rb:74:in `call'
/home/rodrigo/.rbenv/versions/jruby-9.1.2.0/lib/ruby/gems/shared/gems/puma-3.4.0-java/lib/puma/configuration.rb:224:in `call'
```

**Comment by jeremyevans** [comment]
You should only be getting that if you are trying to reload a file that loads those constants.  My guess is you are trying to setup reloading a file that requires one of those java libraries.  One solution would be to move the requiring of those java libraries into the app initialization code.  The other would be to use a proc when setting up the reloader, so it only reloads the classes you specify.

I think the problem you are experiencing can happen in certain cases in MRI (with frozen classes), it's not specific to JRuby.

Personally, in all of my applications that use rack-unreloader I pass a block to `Unreloader.require` to specify which classes should be reloaded.  Even if it works without the block, the performance is much better with the block as it doesn't have to traverse ObjectSpace.

**Comment by rosenfeld** [comment]
Yes, this is how it was using yesterday since it was the only option for JRuby 9.0.5.0. It's probably fine for that app, since it's pretty small, but while evaluating moving my main application to Sequel, I'd probably prefer not to have to worry about which constants each dependency will create... The main application runs on MRI, so maybe I don't get this kind of problem. I'll see and if it gets slow I can try to always provide the block.

In any case, I don't intend to change the way I require code, which is basically in the places I need them, that's why I don't like moving the java libraries requires to the app's initialization (or duplicating them there just to work around issues with the reloader)... I guess I'll figure out what works better as I'm moving parts of the application to the Roda app.

**Comment by rosenfeld** [comment]
It seems this is what's happening:

```
Java::OrgApachePoiHssfUsermodel.send(:remove_const, 'HSSFWorkbook')
ArgumentError: Java package 'org.apache.poi.hssf.usermodel' does not have a method `send' with 2 arguments
```

Maybe rack-unreloader treat such constants differently when running on JRuby and do not attempt to remove any constant where `constant.to_s.start_with?('Java::')`?

**Comment by jeremyevans** [comment]
Like I mentioned, I don't want to work around implementation specific bugs.  I am open to refactoring so you could easily override the behavior.  Basically, add a method that does `!mod.name.to_s.empty?` that you could override if you want to skip the handling of a module.  Please submit a pull request if you'd like to do that.

**Comment by jeremyevans** [comment]
Yep, that definitely looks like the best workaround.

**Comment by rosenfeld** [comment]
You should probably include this require in unreloader.rb:

```ruby
require_relative './unreloader/reloader'
```

**Comment by rosenfeld** [comment]
Actually that snippet didn't work, I just tested. I'll try to understand the reason tomorrow, the babysitter is leaving and I have to stay with the kids now...

**Comment by jeremyevans** [comment]
The reason it doesn't do that is it only loads that file in reload mode.  If you use `:reload=>false` when initializing Rack::Unreloader, the file isn't loaded or used.  This allows you to have the same code in development and production, and only enable reloading in development.

Also, require_relative is not available in ruby 1.8, which rack-unreloader still supports.

**Comment by rosenfeld** [comment]
I see. Any ideas on why I can't override remove_constant by including a module in Reloader?

**Comment by jeremyevans** [comment]
It should work if you use `prepend` instead of `include`. As an advanced ruby user I am sure you are aware of how ruby's method lookup works in regards to classes and included modules.

**Comment by rosenfeld** [comment]
That's right, thank you, I'll try that tomorrow but I already know there are other bugs as I changed the code directly in the source and noticed that it wasn't finding RailsCompatibleCookiesUtils even though it was required in app.rb. I'll continue my research tomorrow.
